2025-03-26 14:37:52,840 - Datasciencelogger - INFO - Hello World
2025-04-02 11:20:34,381 - Datasciencelogger - ERROR - Error reading the yaml file: [Errno 2] No such file or directory: 'config\\config.yaml'
2025-04-02 11:23:04,166 - Datasciencelogger - ERROR - Error reading the yaml file: [Errno 2] No such file or directory: 'config\\config.yaml'
2025-04-02 11:45:23,949 - Datasciencelogger - ERROR - Error reading the yaml file: [Errno 2] No such file or directory: 'config\\config.yaml'
2025-04-05 10:46:13,704 - Datasciencelogger - ERROR - Error reading the yaml file: [Errno 2] No such file or directory: 'config\\config.yaml'
2025-04-05 10:54:19,850 - Datasciencelogger - ERROR - Error reading the yaml file: [Errno 2] No such file or directory: 'config\\config.yaml'
2025-04-05 10:54:42,819 - Datasciencelogger - ERROR - Error reading the yaml file: [Errno 2] No such file or directory: 'config\\config.yaml'
2025-04-05 11:13:37,033 - Datasciencelogger - INFO - Directory created for artifacts
2025-04-05 11:22:06,179 - Datasciencelogger - INFO - Directory created for artifacts
2025-04-05 11:23:05,042 - Datasciencelogger - INFO - Directory created for artifacts
2025-04-05 11:24:52,598 - Datasciencelogger - INFO - Directory created for artifacts
2025-04-05 11:27:53,437 - Datasciencelogger - INFO - Directory created for artifacts
2025-04-05 11:33:51,686 - Datasciencelogger - INFO - Directory created for artifacts
2025-04-05 11:35:49,093 - Datasciencelogger - INFO - Directory already exists for artifacts
2025-04-05 11:35:57,764 - Datasciencelogger - INFO - Directory already exists for artifacts
2025-04-05 11:37:40,909 - Datasciencelogger - INFO - Directory already exists for artifacts
2025-04-05 11:37:56,262 - Datasciencelogger - INFO - Directory already exists for artifacts
2025-04-05 11:39:35,211 - Datasciencelogger - ERROR - Permission error: [WinError 5] Accès refusé: 'artifacts'
2025-04-05 11:41:11,086 - Datasciencelogger - INFO - Directory already exists for artifacts
2025-04-05 11:42:31,561 - Datasciencelogger - INFO - Directory already exists for artifacts
2025-04-05 11:43:17,849 - Datasciencelogger - INFO - Directory already exists for artifacts
2025-04-05 11:45:34,540 - Datasciencelogger - INFO - Directory already exists for artifacts
2025-04-05 11:49:14,854 - Datasciencelogger - INFO - Directory already exists for artifacts
2025-04-05 11:55:36,400 - Datasciencelogger - INFO - Directory already exists for artifacts
2025-04-05 11:56:34,003 - Datasciencelogger - INFO - Directory already exists for artifacts
2025-04-05 11:57:56,993 - Datasciencelogger - INFO - Directory already exists for artifacts
2025-04-05 11:59:07,822 - Datasciencelogger - INFO - Directory already exists for artifacts
2025-04-05 12:05:49,564 - Datasciencelogger - INFO - Directory already exists for artifacts
2025-04-05 12:27:28,612 - Datasciencelogger - INFO - Directory already exists for artifacts
2025-04-05 12:27:28,626 - Datasciencelogger - INFO - Directory created for artifacts/data_ingestion
2025-04-05 12:27:33,428 - Datasciencelogger - INFO - artifacts/data_ingestion/data.zip downloaded: 
  Connection: close
Content-Length: 23329
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "c69888a4ae59bc5a893392785a938ccd4937981c06ba8a9d6a21aa52b4ab5b6e"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: 979B:15C75F:1857FEC:1BD1067:67F10595
Accept-Ranges: bytes
Date: Sat, 05 Apr 2025 10:27:33 GMT
Via: 1.1 varnish
X-Served-By: cache-par-lfpb1150054-PAR
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1743848853.262432,VS0,VE160
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: 689298939a68dd39439e917e0a4f658b15c048a6
Expires: Sat, 05 Apr 2025 10:32:33 GMT
Source-Age: 0


2025-04-05 12:27:33,473 - Datasciencelogger - INFO - Extracted files to artifacts/data_ingestion
2025-04-05 12:30:48,646 - Datasciencelogger - INFO - Directory already exists for artifacts
2025-04-05 12:30:48,664 - Datasciencelogger - INFO - Directory created for artifacts/data_ingestion
2025-04-05 12:30:51,331 - Datasciencelogger - INFO - artifacts/data_ingestion/data.zip downloaded: 
  Connection: close
Content-Length: 23329
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "c69888a4ae59bc5a893392785a938ccd4937981c06ba8a9d6a21aa52b4ab5b6e"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: 979B:15C75F:1857FEC:1BD1067:67F10595
Accept-Ranges: bytes
Date: Sat, 05 Apr 2025 10:30:51 GMT
Via: 1.1 varnish
X-Served-By: cache-par-lfpb1150069-PAR
X-Cache: HIT
X-Cache-Hits: 0
X-Timer: S1743849051.442837,VS0,VE1
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: e47e8fa529d6143a817b36aae71221a736bd713d
Expires: Sat, 05 Apr 2025 10:35:51 GMT
Source-Age: 198


2025-04-05 12:30:51,369 - Datasciencelogger - INFO - Extracted files to artifacts/data_ingestion
2025-04-05 12:35:41,126 - Datasciencelogger - INFO - Directory already exists for artifacts
2025-04-05 12:35:41,133 - Datasciencelogger - INFO - Directory already exists for artifacts/data_ingestion
2025-04-05 12:35:41,142 - Datasciencelogger - INFO - File already exists: artifacts/data_ingestion/data.zip
2025-04-05 12:35:41,168 - Datasciencelogger - INFO - Extracted files to artifacts/data_ingestion
2025-04-05 12:36:06,526 - Datasciencelogger - INFO - Directory already exists for artifacts
2025-04-05 12:36:06,540 - Datasciencelogger - INFO - Directory already exists for artifacts/data_ingestion
2025-04-05 12:36:06,544 - Datasciencelogger - INFO - File already exists: artifacts/data_ingestion/data.zip
2025-04-05 12:36:06,565 - Datasciencelogger - INFO - Extracted files to artifacts/data_ingestion
2025-04-05 12:36:34,232 - Datasciencelogger - INFO - Directory already exists for artifacts
2025-04-05 12:37:14,921 - Datasciencelogger - INFO - Directory already exists for artifacts
2025-04-05 12:37:14,929 - Datasciencelogger - INFO - Directory created for artifacts/data_ingestion
2025-04-05 12:37:16,906 - Datasciencelogger - INFO - artifacts/data_ingestion/data.zip downloaded: 
  Connection: close
Content-Length: 23329
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "c69888a4ae59bc5a893392785a938ccd4937981c06ba8a9d6a21aa52b4ab5b6e"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: 979B:15C75F:1857FEC:1BD1067:67F10595
Accept-Ranges: bytes
Date: Sat, 05 Apr 2025 10:37:17 GMT
Via: 1.1 varnish
X-Served-By: cache-par-lfpb1150021-PAR
X-Cache: HIT
X-Cache-Hits: 0
X-Timer: S1743849437.872100,VS0,VE143
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: f31b64049c23efcda9cd333823d1e03d654bff7e
Expires: Sat, 05 Apr 2025 10:42:17 GMT
Source-Age: 0


2025-04-05 12:37:16,906 - Datasciencelogger - INFO - Extracted files to artifacts/data_ingestion
2025-04-05 12:39:18,438 - Datasciencelogger - INFO - Directory created for artifacts
2025-04-05 12:39:18,444 - Datasciencelogger - INFO - Directory created for artifacts/data_ingestion
2025-04-05 12:39:20,253 - Datasciencelogger - INFO - artifacts/data_ingestion/data.zip downloaded: 
  Connection: close
Content-Length: 23329
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "c69888a4ae59bc5a893392785a938ccd4937981c06ba8a9d6a21aa52b4ab5b6e"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: 979B:15C75F:1857FEC:1BD1067:67F10595
Accept-Ranges: bytes
Date: Sat, 05 Apr 2025 10:39:20 GMT
Via: 1.1 varnish
X-Served-By: cache-par-lfpb1150036-PAR
X-Cache: HIT
X-Cache-Hits: 0
X-Timer: S1743849560.340814,VS0,VE1
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: 16635dddbb7acdeb0ba48bf957df4d0df3c3427f
Expires: Sat, 05 Apr 2025 10:44:20 GMT
Source-Age: 123


2025-04-05 12:39:20,271 - Datasciencelogger - INFO - Extracted files to artifacts/data_ingestion
2025-04-05 12:39:34,175 - Datasciencelogger - INFO - Directory already exists for artifacts
2025-04-05 12:39:34,182 - Datasciencelogger - INFO - Directory created for artifacts/data_ingestion
2025-04-05 12:39:36,571 - Datasciencelogger - INFO - artifacts/data_ingestion/data.zip downloaded: 
  Connection: close
Content-Length: 23329
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "c69888a4ae59bc5a893392785a938ccd4937981c06ba8a9d6a21aa52b4ab5b6e"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: 979B:15C75F:1857FEC:1BD1067:67F10595
Accept-Ranges: bytes
Date: Sat, 05 Apr 2025 10:39:36 GMT
Via: 1.1 varnish
X-Served-By: cache-par-lfpb1150031-PAR
X-Cache: HIT
X-Cache-Hits: 1
X-Timer: S1743849577.678626,VS0,VE1
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: 6056a38ca72be02f79eb90ebad41ba815bb162a1
Expires: Sat, 05 Apr 2025 10:44:36 GMT
Source-Age: 140


2025-04-05 12:39:36,581 - Datasciencelogger - INFO - Extracted files to artifacts/data_ingestion
2025-04-05 12:39:58,183 - Datasciencelogger - INFO - Directory already exists for artifacts
2025-04-05 12:39:58,186 - Datasciencelogger - INFO - Directory created for artifacts/data_ingestion
2025-04-05 12:39:59,485 - Datasciencelogger - INFO - artifacts/data_ingestion/data.zip downloaded: 
  Connection: close
Content-Length: 23329
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "c69888a4ae59bc5a893392785a938ccd4937981c06ba8a9d6a21aa52b4ab5b6e"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: 979B:15C75F:1857FEC:1BD1067:67F10595
Accept-Ranges: bytes
Date: Sat, 05 Apr 2025 10:39:59 GMT
Via: 1.1 varnish
X-Served-By: cache-par-lfpb1150038-PAR
X-Cache: HIT
X-Cache-Hits: 1
X-Timer: S1743849600.593243,VS0,VE1
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: 69cc80eea8b827454fae308e1f5328bdc1596de1
Expires: Sat, 05 Apr 2025 10:44:59 GMT
Source-Age: 163


2025-04-05 12:39:59,485 - Datasciencelogger - INFO - Extracted files to artifacts/data_ingestion
2025-04-05 13:42:50,887 - Datasciencelogger - INFO - Bienvenue dans mon projet de data science !
2025-04-05 13:47:40,718 - Datasciencelogger - INFO - Bienvenue dans mon projet de data science !
2025-04-05 13:47:40,718 - Datasciencelogger - INFO - >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> Data Ingestion stage started <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2025-04-05 13:47:40,724 - Datasciencelogger - ERROR - DataIngestionTrainingPipeline.__init__() missing 1 required positional argument: 'config'
Traceback (most recent call last):
  File "C:\Users\sylla\Desktop\MLOPS\Project1_with_deployment\Project1_Data_Science\main.py", line 9, in <module>
    obj = DataIngestionTrainingPipeline()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: DataIngestionTrainingPipeline.__init__() missing 1 required positional argument: 'config'
2025-04-05 13:48:10,105 - Datasciencelogger - INFO - Bienvenue dans mon projet de data science !
2025-04-05 13:48:10,108 - Datasciencelogger - INFO - >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> Data Ingestion stage started <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2025-04-05 13:48:10,108 - Datasciencelogger - ERROR - DataIngestionTrainingPipeline.__init__() missing 1 required positional argument: 'config'
Traceback (most recent call last):
  File "C:\Users\sylla\Desktop\MLOPS\Project1_with_deployment\Project1_Data_Science\main.py", line 9, in <module>
    obj = DataIngestionTrainingPipeline()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: DataIngestionTrainingPipeline.__init__() missing 1 required positional argument: 'config'
2025-04-05 13:48:34,401 - Datasciencelogger - INFO - Bienvenue dans mon projet de data science !
2025-04-05 13:48:34,403 - Datasciencelogger - INFO - >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> Data Ingestion stage started <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2025-04-05 13:48:34,403 - Datasciencelogger - ERROR - DataIngestionTrainingPipeline.__init__() missing 1 required positional argument: 'config'
Traceback (most recent call last):
  File "C:\Users\sylla\Desktop\MLOPS\Project1_with_deployment\Project1_Data_Science\main.py", line 9, in <module>
    obj = DataIngestionTrainingPipeline()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: DataIngestionTrainingPipeline.__init__() missing 1 required positional argument: 'config'
2025-04-05 13:51:49,024 - Datasciencelogger - INFO - Bienvenue dans mon projet de data science !
2025-04-05 13:51:49,024 - Datasciencelogger - INFO - >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> Data Ingestion stage started <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2025-04-05 13:51:49,024 - Datasciencelogger - ERROR - 'DataIngestionTrainingPipeline' object has no attribute 'config'
Traceback (most recent call last):
  File "C:\Users\sylla\Desktop\MLOPS\Project1_with_deployment\Project1_Data_Science\main.py", line 10, in <module>
    obj.initiate_data_ingestion()
  File "C:\Users\sylla\Desktop\MLOPS\Project1_with_deployment\Project1_Data_Science\src\Project1_Data_Science\pipeline\data_ingestion.py", line 14, in initiate_data_ingestion
    data_ingestion_config = self.config.get_ingestion_config()
                            ^^^^^^^^^^^
AttributeError: 'DataIngestionTrainingPipeline' object has no attribute 'config'
2025-04-05 13:52:06,874 - Datasciencelogger - INFO - Bienvenue dans mon projet de data science !
2025-04-05 13:52:06,876 - Datasciencelogger - INFO - >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> Data Ingestion stage started <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2025-04-05 13:52:06,876 - Datasciencelogger - ERROR - 'DataIngestionTrainingPipeline' object has no attribute 'config'
Traceback (most recent call last):
  File "C:\Users\sylla\Desktop\MLOPS\Project1_with_deployment\Project1_Data_Science\main.py", line 10, in <module>
    obj.initiate_data_ingestion()
  File "C:\Users\sylla\Desktop\MLOPS\Project1_with_deployment\Project1_Data_Science\src\Project1_Data_Science\pipeline\data_ingestion.py", line 14, in initiate_data_ingestion
    data_ingestion_config = self.config.get_ingestion_config()
                            ^^^^^^^^^^^
AttributeError: 'DataIngestionTrainingPipeline' object has no attribute 'config'
2025-04-05 13:53:50,780 - Datasciencelogger - INFO - Bienvenue dans mon projet de data science !
2025-04-05 13:53:50,780 - Datasciencelogger - INFO - >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> Data Ingestion stage started <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2025-04-05 13:53:50,804 - Datasciencelogger - ERROR - isinstance() argument 2 cannot be a parameterized generic
Traceback (most recent call last):
  File "C:\Users\sylla\Desktop\MLOPS\Project1_with_deployment\Project1_Data_Science\main.py", line 10, in <module>
    obj.initiate_data_ingestion()
  File "C:\Users\sylla\Desktop\MLOPS\Project1_with_deployment\Project1_Data_Science\src\Project1_Data_Science\pipeline\data_ingestion.py", line 14, in initiate_data_ingestion
    config = ConfigurationManager()
             ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sylla\Desktop\MLOPS\Project1_with_deployment\Project1_Data_Science\src\Project1_Data_Science\config\configuration.py", line 19, in __init__
    create_directories([str(self.config.artifacts_root)])
  File "C:\Users\sylla\Desktop\MLOPS\Project1_with_deployment\Project1_Data_Science\mon_env\Lib\site-packages\ensure\main.py", line 868, in __call__
    if not isinstance(value, templ):
           ^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: isinstance() argument 2 cannot be a parameterized generic
2025-04-05 13:56:24,247 - Datasciencelogger - INFO - Bienvenue dans mon projet de data science !
2025-04-05 13:56:24,249 - Datasciencelogger - INFO - >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> Data Ingestion stage started <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2025-04-05 13:56:24,285 - Datasciencelogger - INFO - Directory created for artifacts
2025-04-05 13:56:24,297 - Datasciencelogger - INFO - Directory created for artifacts/data_ingestion
2025-04-05 13:56:27,385 - Datasciencelogger - INFO - artifacts/data_ingestion/data.zip downloaded: 
  Connection: close
Content-Length: 23329
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "c69888a4ae59bc5a893392785a938ccd4937981c06ba8a9d6a21aa52b4ab5b6e"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: FAD0:1687A4:1A8C85A:1D7F6D4:67F11A67
Accept-Ranges: bytes
Date: Sat, 05 Apr 2025 11:56:27 GMT
Via: 1.1 varnish
X-Served-By: cache-par-lfpb1150042-PAR
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1743854187.025962,VS0,VE159
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: 81cd31d502ff004a64c3828cea411893d9b04481
Expires: Sat, 05 Apr 2025 12:01:27 GMT
Source-Age: 0


2025-04-05 13:56:27,412 - Datasciencelogger - INFO - Extracted files to artifacts/data_ingestion
2025-04-05 13:56:27,416 - Datasciencelogger - INFO - >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> Data Ingestion stage completed <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2025-04-05 13:57:46,509 - Datasciencelogger - INFO - Bienvenue dans mon projet de data science !
2025-04-05 13:57:46,514 - Datasciencelogger - INFO - >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> Data Ingestion stage started <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2025-04-05 13:57:46,529 - Datasciencelogger - INFO - Directory created for artifacts
2025-04-05 13:57:46,530 - Datasciencelogger - ERROR - isinstance() arg 2 must be a type, a tuple of types, or a union
Traceback (most recent call last):
  File "C:\Users\sylla\Desktop\MLOPS\Project1_with_deployment\Project1_Data_Science\main.py", line 10, in <module>
    obj.initiate_data_ingestion()
  File "C:\Users\sylla\Desktop\MLOPS\Project1_with_deployment\Project1_Data_Science\src\Project1_Data_Science\pipeline\data_ingestion.py", line 14, in initiate_data_ingestion
    config = ConfigurationManager()
             ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sylla\Desktop\MLOPS\Project1_with_deployment\Project1_Data_Science\src\Project1_Data_Science\config\configuration.py", line 19, in __init__
    create_directories([str(self.config.artifacts_root)])
  File "C:\Users\sylla\Desktop\MLOPS\Project1_with_deployment\Project1_Data_Science\mon_env\Lib\site-packages\ensure\main.py", line 873, in __call__
    if not isinstance(return_val, self.return_templ):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: isinstance() arg 2 must be a type, a tuple of types, or a union
2025-04-05 13:58:29,819 - Datasciencelogger - INFO - Bienvenue dans mon projet de data science !
2025-04-05 13:58:29,822 - Datasciencelogger - INFO - >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> Data Ingestion stage started <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2025-04-05 13:58:29,845 - Datasciencelogger - INFO - Directory already exists for artifacts
2025-04-05 13:58:29,848 - Datasciencelogger - INFO - Directory created for artifacts/data_ingestion
2025-04-05 13:58:30,834 - Datasciencelogger - INFO - artifacts/data_ingestion/data.zip downloaded: 
  Connection: close
Content-Length: 23329
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "c69888a4ae59bc5a893392785a938ccd4937981c06ba8a9d6a21aa52b4ab5b6e"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: FAD0:1687A4:1A8C85A:1D7F6D4:67F11A67
Accept-Ranges: bytes
Date: Sat, 05 Apr 2025 11:58:30 GMT
Via: 1.1 varnish
X-Served-By: cache-par-lfpb1150074-PAR
X-Cache: HIT
X-Cache-Hits: 0
X-Timer: S1743854311.737492,VS0,VE3
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: 28f0a492a729a983267565266ce883bd4a17631c
Expires: Sat, 05 Apr 2025 12:03:30 GMT
Source-Age: 124


2025-04-05 13:58:30,850 - Datasciencelogger - INFO - Extracted files to artifacts/data_ingestion
2025-04-05 13:58:30,854 - Datasciencelogger - INFO - >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> Data Ingestion stage completed <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2025-04-05 13:59:50,855 - Datasciencelogger - INFO - Bienvenue dans mon projet de data science !
2025-04-05 13:59:50,857 - Datasciencelogger - INFO - >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> Data Ingestion stage started <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2025-04-05 13:59:50,880 - Datasciencelogger - INFO - Directory already exists for artifacts
2025-04-05 13:59:50,880 - Datasciencelogger - ERROR - isinstance() arg 2 must be a type, a tuple of types, or a union
Traceback (most recent call last):
  File "C:\Users\sylla\Desktop\MLOPS\Project1_with_deployment\Project1_Data_Science\main.py", line 10, in <module>
    obj.initiate_data_ingestion()
  File "C:\Users\sylla\Desktop\MLOPS\Project1_with_deployment\Project1_Data_Science\src\Project1_Data_Science\pipeline\data_ingestion.py", line 14, in initiate_data_ingestion
    config = ConfigurationManager()
             ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sylla\Desktop\MLOPS\Project1_with_deployment\Project1_Data_Science\src\Project1_Data_Science\config\configuration.py", line 19, in __init__
    create_directories([self.config.artifacts_root])
  File "C:\Users\sylla\Desktop\MLOPS\Project1_with_deployment\Project1_Data_Science\mon_env\Lib\site-packages\ensure\main.py", line 873, in __call__
    if not isinstance(return_val, self.return_templ):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: isinstance() arg 2 must be a type, a tuple of types, or a union
2025-04-05 14:00:07,160 - Datasciencelogger - INFO - Bienvenue dans mon projet de data science !
2025-04-05 14:00:07,160 - Datasciencelogger - INFO - >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> Data Ingestion stage started <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2025-04-05 14:00:07,180 - Datasciencelogger - INFO - Directory already exists for artifacts
2025-04-05 14:00:07,184 - Datasciencelogger - INFO - Directory already exists for artifacts/data_ingestion
2025-04-05 14:00:07,186 - Datasciencelogger - INFO - File already exists: artifacts/data_ingestion/data.zip
2025-04-05 14:00:07,212 - Datasciencelogger - INFO - Extracted files to artifacts/data_ingestion
2025-04-05 14:00:07,212 - Datasciencelogger - INFO - >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> Data Ingestion stage completed <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2025-04-05 14:00:42,723 - Datasciencelogger - INFO - Bienvenue dans mon projet de data science !
2025-04-05 14:00:42,723 - Datasciencelogger - INFO - >>>>>>>>>>>>>>>>>>>> Data Ingestion stage started <<<<<<<<<<<<<<<<<<<<
2025-04-05 14:00:42,746 - Datasciencelogger - INFO - Directory already exists for artifacts
2025-04-05 14:00:42,746 - Datasciencelogger - INFO - Directory already exists for artifacts/data_ingestion
2025-04-05 14:00:42,750 - Datasciencelogger - INFO - File already exists: artifacts/data_ingestion/data.zip
2025-04-05 14:00:42,770 - Datasciencelogger - INFO - Extracted files to artifacts/data_ingestion
2025-04-05 14:00:42,776 - Datasciencelogger - INFO - >>>>>>>>>>>>>>>>>>>> Data Ingestion stage completed <<<<<<<<<<<<<<<<<<<<
2025-04-05 14:03:04,873 - Datasciencelogger - INFO - Bienvenue dans mon projet de data science !
2025-04-05 14:03:04,876 - Datasciencelogger - INFO - >>>>>>>>>>>>>>>>>>>> Data Ingestion stage started <<<<<<<<<<<<<<<<<<<<
2025-04-05 14:03:04,895 - Datasciencelogger - INFO - Directory already exists for artifacts
2025-04-05 14:03:04,899 - Datasciencelogger - INFO - Directory already exists for artifacts/data_ingestion
2025-04-05 14:03:04,901 - Datasciencelogger - INFO - File already exists: artifacts/data_ingestion/data.zip
2025-04-05 14:03:04,931 - Datasciencelogger - INFO - Extracted files to artifacts/data_ingestion
2025-04-05 14:03:04,931 - Datasciencelogger - INFO - >>>>>>>>>>>>>>>>>>>> Data Ingestion stage completed <<<<<<<<<<<<<<<<<<<<
2025-04-05 14:03:38,477 - Datasciencelogger - INFO - Bienvenue dans mon projet de data science !
2025-04-05 14:03:38,477 - Datasciencelogger - INFO - >>>>>>>>>>>>>>>>>>>> Data Ingestion stage started <<<<<<<<<<<<<<<<<<<<
2025-04-05 14:03:38,501 - Datasciencelogger - INFO - Directory created for artifacts
2025-04-05 14:03:38,510 - Datasciencelogger - INFO - Directory created for artifacts/data_ingestion
2025-04-05 14:03:39,921 - Datasciencelogger - INFO - artifacts/data_ingestion/data.zip downloaded: 
  Connection: close
Content-Length: 23329
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "c69888a4ae59bc5a893392785a938ccd4937981c06ba8a9d6a21aa52b4ab5b6e"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: FAD0:1687A4:1A8C85A:1D7F6D4:67F11A67
Accept-Ranges: bytes
Date: Sat, 05 Apr 2025 12:03:39 GMT
Via: 1.1 varnish
X-Served-By: cache-par-lfpb1150025-PAR
X-Cache: HIT
X-Cache-Hits: 0
X-Timer: S1743854620.601587,VS0,VE147
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: c37fe5c0ec5bd15fb071674e7c64334c994acdd8
Expires: Sat, 05 Apr 2025 12:08:39 GMT
Source-Age: 0


2025-04-05 14:03:39,934 - Datasciencelogger - INFO - Extracted files to artifacts/data_ingestion
2025-04-05 14:03:39,937 - Datasciencelogger - INFO - >>>>>>>>>>>>>>>>>>>> Data Ingestion stage completed <<<<<<<<<<<<<<<<<<<<
2025-04-05 14:09:34,174 - Datasciencelogger - INFO - Bienvenue dans mon projet de data science !
2025-04-05 14:09:34,174 - Datasciencelogger - INFO - >>>>>>>>>>>>>>>>>>>> Data Ingestion stage started <<<<<<<<<<<<<<<<<<<<
2025-04-05 14:09:34,252 - Datasciencelogger - INFO - created directory at: artifacts
2025-04-05 14:09:34,252 - Datasciencelogger - INFO - created directory at: artifacts/data_ingestion
2025-04-05 14:09:34,256 - Datasciencelogger - INFO - File already exists: artifacts/data_ingestion/data.zip
2025-04-05 14:09:34,277 - Datasciencelogger - INFO - Extracted files to artifacts/data_ingestion
2025-04-05 14:09:34,279 - Datasciencelogger - INFO - >>>>>>>>>>>>>>>>>>>> Data Ingestion stage completed <<<<<<<<<<<<<<<<<<<<
2025-04-05 14:10:18,896 - Datasciencelogger - INFO - Bienvenue dans mon projet de data science !
2025-04-05 14:10:18,898 - Datasciencelogger - INFO - >>>>>>>>>>>>>>>>>>>> Data Ingestion stage started <<<<<<<<<<<<<<<<<<<<
2025-04-05 14:10:18,946 - Datasciencelogger - INFO - created directory at: artifacts
2025-04-05 14:10:18,952 - Datasciencelogger - INFO - created directory at: artifacts/data_ingestion
2025-04-05 14:10:20,803 - Datasciencelogger - INFO - artifacts/data_ingestion/data.zip downloaded: 
  Connection: close
Content-Length: 23329
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "c69888a4ae59bc5a893392785a938ccd4937981c06ba8a9d6a21aa52b4ab5b6e"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: FAD0:1687A4:1A8C85A:1D7F6D4:67F11A67
Accept-Ranges: bytes
Date: Sat, 05 Apr 2025 12:10:20 GMT
Via: 1.1 varnish
X-Served-By: cache-par-lfpb1150046-PAR
X-Cache: HIT
X-Cache-Hits: 0
X-Timer: S1743855021.511359,VS0,VE151
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: c9a8fa6d72101df7a9a8a31c33c0968725d97b0f
Expires: Sat, 05 Apr 2025 12:15:20 GMT
Source-Age: 0


2025-04-05 14:10:20,821 - Datasciencelogger - INFO - Extracted files to artifacts/data_ingestion
2025-04-05 14:10:20,821 - Datasciencelogger - INFO - >>>>>>>>>>>>>>>>>>>> Data Ingestion stage completed <<<<<<<<<<<<<<<<<<<<
2025-04-05 19:50:26,501 - Datasciencelogger - INFO - created directory at: artifacts
2025-04-05 19:50:26,507 - Datasciencelogger - INFO - created directory at: artifacts/data_validation
2025-04-05 19:51:30,532 - Datasciencelogger - INFO - created directory at: artifacts
2025-04-05 19:51:30,545 - Datasciencelogger - INFO - created directory at: artifacts/data_validation
2025-04-05 19:51:30,556 - Datasciencelogger - ERROR - An error occurred during data validation.
Traceback (most recent call last):
  File "C:\Users\sylla\AppData\Local\Temp\ipykernel_8660\2457212236.py", line 3, in <module>
    data_validation_config = config.get_data_validation_config()
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sylla\AppData\Local\Temp\ipykernel_8660\3120548061.py", line 19, in get_data_validation_config
    data_validation_config = DataValidationConfig(
                             ^^^^^^^^^^^^^^^^^^^^^
TypeError: DataValidationConfig.__init__() got an unexpected keyword argument 'unzip_data_dir'
2025-04-05 19:51:51,734 - Datasciencelogger - INFO - created directory at: artifacts
2025-04-05 19:51:51,736 - Datasciencelogger - INFO - created directory at: artifacts/data_validation
2025-04-05 19:51:51,739 - Datasciencelogger - ERROR - An error occurred during data validation.
Traceback (most recent call last):
  File "C:\Users\sylla\AppData\Local\Temp\ipykernel_12660\2457212236.py", line 3, in <module>
    data_validation_config = config.get_data_validation_config()
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sylla\AppData\Local\Temp\ipykernel_12660\3120548061.py", line 19, in get_data_validation_config
    data_validation_config = DataValidationConfig(
                             ^^^^^^^^^^^^^^^^^^^^^
TypeError: DataValidationConfig.__init__() got an unexpected keyword argument 'unzip_data_dir'
2025-04-05 19:58:38,517 - Datasciencelogger - INFO - created directory at: artifacts
2025-04-05 19:58:38,524 - Datasciencelogger - INFO - created directory at: artifacts/data_validation
2025-04-05 19:58:38,526 - Datasciencelogger - ERROR - Error occurred during data validation.
Traceback (most recent call last):
  File "C:\Users\sylla\AppData\Local\Temp\ipykernel_12660\4143621680.py", line 10, in validation_all_columns
    data = pd.read_csv(self.config.unzip_data_dir)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DataValidationConfig' object has no attribute 'unzip_data_dir'
2025-04-05 19:58:38,530 - Datasciencelogger - ERROR - An error occurred during data validation.
Traceback (most recent call last):
  File "C:\Users\sylla\AppData\Local\Temp\ipykernel_12660\2457212236.py", line 5, in <module>
    data_validation.validation_all_columns()
  File "C:\Users\sylla\AppData\Local\Temp\ipykernel_12660\4143621680.py", line 32, in validation_all_columns
    raise e
  File "C:\Users\sylla\AppData\Local\Temp\ipykernel_12660\4143621680.py", line 10, in validation_all_columns
    data = pd.read_csv(self.config.unzip_data_dir)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DataValidationConfig' object has no attribute 'unzip_data_dir'
2025-04-05 20:00:07,523 - Datasciencelogger - INFO - created directory at: artifacts
2025-04-05 20:00:07,529 - Datasciencelogger - INFO - created directory at: artifacts/data_validation
2025-04-05 20:00:07,543 - Datasciencelogger - INFO - Data loaded successfully for validation.
2025-04-05 20:00:07,549 - Datasciencelogger - INFO - Column fixed acidity is in the schema.
2025-04-05 20:00:07,556 - Datasciencelogger - INFO - Column volatile acidity is in the schema.
2025-04-05 20:00:07,560 - Datasciencelogger - INFO - Column citric acid is in the schema.
2025-04-05 20:00:07,564 - Datasciencelogger - INFO - Column residual sugar is in the schema.
2025-04-05 20:00:07,571 - Datasciencelogger - INFO - Column chlorides is in the schema.
2025-04-05 20:00:07,575 - Datasciencelogger - INFO - Column free sulfur dioxide is in the schema.
2025-04-05 20:00:07,580 - Datasciencelogger - INFO - Column total sulfur dioxide is in the schema.
2025-04-05 20:00:07,586 - Datasciencelogger - INFO - Column density is in the schema.
2025-04-05 20:00:07,592 - Datasciencelogger - INFO - Column pH is in the schema.
2025-04-05 20:00:07,596 - Datasciencelogger - INFO - Column sulphates is in the schema.
2025-04-05 20:00:07,605 - Datasciencelogger - INFO - Column alcohol is in the schema.
2025-04-05 20:00:07,609 - Datasciencelogger - INFO - Column quality is in the schema.
2025-04-05 20:00:07,612 - Datasciencelogger - INFO - Data validation completed successfully.
2025-04-05 20:06:12,682 - Datasciencelogger - INFO - created directory at: artifacts
2025-04-05 20:06:12,716 - Datasciencelogger - INFO - created directory at: artifacts/data_validation
2025-04-05 20:06:12,724 - Datasciencelogger - ERROR - An error occurred during data validation.
Traceback (most recent call last):
  File "c:\Users\sylla\Desktop\MLOPS\Project1_with_deployment\Project1_Data_Science\mon_env\Lib\site-packages\box\box.py", line 503, in __getitem__
    return super().__getitem__(item)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'unzip_data'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\sylla\Desktop\MLOPS\Project1_with_deployment\Project1_Data_Science\mon_env\Lib\site-packages\box\box.py", line 536, in __getattr__
    value = self.__getitem__(item, _ignore_default=True)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sylla\Desktop\MLOPS\Project1_with_deployment\Project1_Data_Science\mon_env\Lib\site-packages\box\box.py", line 524, in __getitem__
    raise BoxKeyError(str(err)) from _exception_cause(err)
box.exceptions.BoxKeyError: "'unzip_data'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\sylla\Desktop\MLOPS\Project1_with_deployment\Project1_Data_Science\mon_env\Lib\site-packages\box\box.py", line 538, in __getattr__
    value = object.__getattribute__(self, item)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigBox' object has no attribute 'unzip_data'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\sylla\Desktop\MLOPS\Project1_with_deployment\Project1_Data_Science\mon_env\Lib\site-packages\box\config_box.py", line 28, in __getattr__
    return super().__getattr__(item)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sylla\Desktop\MLOPS\Project1_with_deployment\Project1_Data_Science\mon_env\Lib\site-packages\box\box.py", line 552, in __getattr__
    raise BoxKeyError(str(err)) from _exception_cause(err)
box.exceptions.BoxKeyError: "'ConfigBox' object has no attribute 'unzip_data'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\sylla\Desktop\MLOPS\Project1_with_deployment\Project1_Data_Science\mon_env\Lib\site-packages\box\box.py", line 503, in __getitem__
    return super().__getitem__(item)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'unzip_data'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\sylla\Desktop\MLOPS\Project1_with_deployment\Project1_Data_Science\mon_env\Lib\site-packages\box\box.py", line 536, in __getattr__
    value = self.__getitem__(item, _ignore_default=True)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sylla\Desktop\MLOPS\Project1_with_deployment\Project1_Data_Science\mon_env\Lib\site-packages\box\box.py", line 524, in __getitem__
    raise BoxKeyError(str(err)) from _exception_cause(err)
box.exceptions.BoxKeyError: "'unzip_data'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\sylla\Desktop\MLOPS\Project1_with_deployment\Project1_Data_Science\mon_env\Lib\site-packages\box\box.py", line 538, in __getattr__
    value = object.__getattribute__(self, item)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigBox' object has no attribute 'unzip_data'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\sylla\AppData\Local\Temp\ipykernel_4288\2457212236.py", line 3, in <module>
    data_validation_config = config.get_data_validation_config()
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sylla\AppData\Local\Temp\ipykernel_4288\3560068624.py", line 22, in get_data_validation_config
    unzip_data=config.unzip_data,
             ^^^^^^^^^^^^^^^^^
  File "c:\Users\sylla\Desktop\MLOPS\Project1_with_deployment\Project1_Data_Science\mon_env\Lib\site-packages\box\config_box.py", line 30, in __getattr__
    return super().__getattr__(item.lower())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sylla\Desktop\MLOPS\Project1_with_deployment\Project1_Data_Science\mon_env\Lib\site-packages\box\box.py", line 552, in __getattr__
    raise BoxKeyError(str(err)) from _exception_cause(err)
box.exceptions.BoxKeyError: "'ConfigBox' object has no attribute 'unzip_data'"
2025-04-05 20:13:41,125 - Datasciencelogger - INFO - created directory at: artifacts
2025-04-05 20:13:41,127 - Datasciencelogger - INFO - created directory at: artifacts/data_validation
2025-04-05 20:13:41,140 - Datasciencelogger - INFO - Data loaded successfully for validation.
2025-04-05 20:13:41,148 - Datasciencelogger - INFO - Column fixed acidity is in the schema.
2025-04-05 20:13:41,152 - Datasciencelogger - INFO - Column volatile acidity is in the schema.
2025-04-05 20:13:41,156 - Datasciencelogger - INFO - Column citric acid is in the schema.
2025-04-05 20:13:41,165 - Datasciencelogger - INFO - Column residual sugar is in the schema.
2025-04-05 20:13:41,168 - Datasciencelogger - INFO - Column chlorides is in the schema.
2025-04-05 20:13:41,173 - Datasciencelogger - INFO - Column free sulfur dioxide is in the schema.
2025-04-05 20:13:41,175 - Datasciencelogger - INFO - Column total sulfur dioxide is in the schema.
2025-04-05 20:13:41,183 - Datasciencelogger - INFO - Column density is in the schema.
2025-04-05 20:13:41,187 - Datasciencelogger - INFO - Column pH is in the schema.
2025-04-05 20:13:41,191 - Datasciencelogger - INFO - Column sulphates is in the schema.
2025-04-05 20:13:41,197 - Datasciencelogger - INFO - Column alcohol is in the schema.
2025-04-05 20:13:41,202 - Datasciencelogger - INFO - Column quality is in the schema.
2025-04-05 20:13:41,205 - Datasciencelogger - INFO - Data validation completed successfully.
2025-04-06 13:56:00,692 - Datasciencelogger - INFO - Bienvenue dans mon projet de data science !
2025-04-06 13:56:00,696 - Datasciencelogger - INFO - >>>>>>>>>>>>>>>>>>>> Data Ingestion stage started <<<<<<<<<<<<<<<<<<<<
2025-04-06 13:56:00,719 - Datasciencelogger - INFO - created directory at: artifacts
2025-04-06 13:56:00,724 - Datasciencelogger - INFO - created directory at: artifacts/data_ingestion
2025-04-06 13:56:02,305 - Datasciencelogger - INFO - artifacts/data_ingestion/data.zip downloaded: 
  Connection: close
Content-Length: 23329
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "c69888a4ae59bc5a893392785a938ccd4937981c06ba8a9d6a21aa52b4ab5b6e"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: 2E38:115D:A0045D:B90BCF:67F26BCE
Accept-Ranges: bytes
Date: Sun, 06 Apr 2025 11:56:02 GMT
Via: 1.1 varnish
X-Served-By: cache-par-lfpb1150037-PAR
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1743940563.792926,VS0,VE164
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: cf0487fae0c47a6a559a057902c160bf44e8b580
Expires: Sun, 06 Apr 2025 12:01:02 GMT
Source-Age: 0


2025-04-06 13:56:02,322 - Datasciencelogger - INFO - Extracted files to artifacts/data_ingestion
2025-04-06 13:56:02,322 - Datasciencelogger - INFO - >>>>>>>>>>>>>>>>>>>> Data Ingestion stage completed <<<<<<<<<<<<<<<<<<<<
2025-04-06 13:56:02,326 - Datasciencelogger - INFO - >>>>>>>>>>>>>>>>>>>> Data Validation stage started <<<<<<<<<<<<<<<<<<<<
2025-04-06 13:56:02,358 - Datasciencelogger - INFO - created directory at: artifacts
2025-04-06 13:56:02,372 - Datasciencelogger - INFO - created directory at: artifacts/data_validation
2025-04-06 13:56:02,436 - Datasciencelogger - INFO - Data loaded successfully for validation.
2025-04-06 13:56:02,442 - Datasciencelogger - INFO - Column fixed acidity is in the schema.
2025-04-06 13:56:02,446 - Datasciencelogger - INFO - Column volatile acidity is in the schema.
2025-04-06 13:56:02,450 - Datasciencelogger - INFO - Column citric acid is in the schema.
2025-04-06 13:56:02,454 - Datasciencelogger - INFO - Column residual sugar is in the schema.
2025-04-06 13:56:02,458 - Datasciencelogger - INFO - Column chlorides is in the schema.
2025-04-06 13:56:02,466 - Datasciencelogger - INFO - Column free sulfur dioxide is in the schema.
2025-04-06 13:56:02,470 - Datasciencelogger - INFO - Column total sulfur dioxide is in the schema.
2025-04-06 13:56:02,476 - Datasciencelogger - INFO - Column density is in the schema.
2025-04-06 13:56:02,484 - Datasciencelogger - INFO - Column pH is in the schema.
2025-04-06 13:56:02,490 - Datasciencelogger - INFO - Column sulphates is in the schema.
2025-04-06 13:56:02,498 - Datasciencelogger - INFO - Column alcohol is in the schema.
2025-04-06 13:56:02,506 - Datasciencelogger - INFO - Column quality is in the schema.
2025-04-06 13:56:02,510 - Datasciencelogger - INFO - Data validation completed successfully.
2025-04-06 13:56:02,514 - Datasciencelogger - INFO - >>>>>>>>>>>>>>>>>>>> Data Validation stage completed <<<<<<<<<<<<<<<<<<<<
2025-04-06 14:54:11,751 - Datasciencelogger - INFO - created directory at: artifacts
2025-04-06 14:54:11,754 - Datasciencelogger - INFO - created directory at: artifacts/data_validation
2025-04-06 14:54:11,772 - Datasciencelogger - INFO - Data loaded successfully for validation.
2025-04-06 14:54:11,789 - Datasciencelogger - INFO - Column fixed acidity is in the schema.
2025-04-06 14:54:11,795 - Datasciencelogger - INFO - Column volatile acidity is in the schema.
2025-04-06 14:54:11,804 - Datasciencelogger - INFO - Column citric acid is in the schema.
2025-04-06 14:54:11,808 - Datasciencelogger - INFO - Column residual sugar is in the schema.
2025-04-06 14:54:11,814 - Datasciencelogger - INFO - Column chlorides is in the schema.
2025-04-06 14:54:11,821 - Datasciencelogger - INFO - Column free sulfur dioxide is in the schema.
2025-04-06 14:54:11,825 - Datasciencelogger - INFO - Column total sulfur dioxide is in the schema.
2025-04-06 14:54:11,829 - Datasciencelogger - INFO - Column density is in the schema.
2025-04-06 14:54:11,837 - Datasciencelogger - INFO - Column pH is in the schema.
2025-04-06 14:54:11,841 - Datasciencelogger - INFO - Column sulphates is in the schema.
2025-04-06 14:54:11,845 - Datasciencelogger - INFO - Column alcohol is in the schema.
2025-04-06 14:54:11,859 - Datasciencelogger - INFO - Column quality is in the schema.
2025-04-06 14:54:11,867 - Datasciencelogger - INFO - Data validation completed successfully.
2025-04-06 16:06:24,581 - Datasciencelogger - INFO - created directory at: artifacts
2025-04-06 16:06:24,594 - Datasciencelogger - INFO - created directory at: artifacts/data_transformation
2025-04-06 16:06:24,610 - Datasciencelogger - INFO - Splitting data into train and test sets.
2025-04-06 16:06:25,137 - Datasciencelogger - INFO - Data splitting completed.
2025-04-06 16:06:25,137 - Datasciencelogger - INFO - (1279, 12)
2025-04-06 16:06:25,137 - Datasciencelogger - INFO - (320, 12)
2025-04-06 17:11:42,460 - Datasciencelogger - INFO - Bienvenue dans mon projet de data science !
2025-04-06 17:11:42,464 - Datasciencelogger - INFO - >>>>>>>>>>>>>>>>>>>> Data Ingestion stage started <<<<<<<<<<<<<<<<<<<<
2025-04-06 17:11:42,503 - Datasciencelogger - INFO - created directory at: artifacts
2025-04-06 17:11:42,517 - Datasciencelogger - INFO - created directory at: artifacts/data_ingestion
2025-04-06 17:11:42,545 - Datasciencelogger - INFO - File already exists: artifacts/data_ingestion/data.zip
2025-04-06 17:11:42,605 - Datasciencelogger - INFO - Extracted files to artifacts/data_ingestion
2025-04-06 17:11:42,607 - Datasciencelogger - INFO - >>>>>>>>>>>>>>>>>>>> Data Ingestion stage completed <<<<<<<<<<<<<<<<<<<<
2025-04-06 17:11:42,609 - Datasciencelogger - INFO - >>>>>>>>>>>>>>>>>>>> Data Validation stage started <<<<<<<<<<<<<<<<<<<<
2025-04-06 17:11:42,645 - Datasciencelogger - INFO - created directory at: artifacts
2025-04-06 17:11:42,655 - Datasciencelogger - INFO - created directory at: artifacts/data_validation
2025-04-06 17:11:42,685 - Datasciencelogger - INFO - Data loaded successfully for validation.
2025-04-06 17:11:42,697 - Datasciencelogger - INFO - Column fixed acidity is in the schema.
2025-04-06 17:11:42,700 - Datasciencelogger - INFO - Column volatile acidity is in the schema.
2025-04-06 17:11:42,780 - Datasciencelogger - INFO - Column citric acid is in the schema.
2025-04-06 17:11:42,795 - Datasciencelogger - INFO - Column residual sugar is in the schema.
2025-04-06 17:11:42,802 - Datasciencelogger - INFO - Column chlorides is in the schema.
2025-04-06 17:11:42,828 - Datasciencelogger - INFO - Column free sulfur dioxide is in the schema.
2025-04-06 17:11:42,849 - Datasciencelogger - INFO - Column total sulfur dioxide is in the schema.
2025-04-06 17:11:42,867 - Datasciencelogger - INFO - Column density is in the schema.
2025-04-06 17:11:42,875 - Datasciencelogger - INFO - Column pH is in the schema.
2025-04-06 17:11:42,879 - Datasciencelogger - INFO - Column sulphates is in the schema.
2025-04-06 17:11:42,887 - Datasciencelogger - INFO - Column alcohol is in the schema.
2025-04-06 17:11:42,897 - Datasciencelogger - INFO - Column quality is in the schema.
2025-04-06 17:11:42,901 - Datasciencelogger - INFO - Data validation completed successfully.
2025-04-06 17:11:42,914 - Datasciencelogger - INFO - >>>>>>>>>>>>>>>>>>>> Data Validation stage completed <<<<<<<<<<<<<<<<<<<<
2025-04-06 17:11:42,917 - Datasciencelogger - INFO - >>>>>>>>>>>>>>>>>>>> Data Transformation stage started <<<<<<<<<<<<<<<<<<<<
2025-04-06 17:11:42,923 - Datasciencelogger - ERROR - empty separator
Traceback (most recent call last):
  File "C:\Users\sylla\Desktop\MLOPS\Project1_with_deployment\Project1_Data_Science\src\Project1_Data_Science\pipeline\data_transforamtion_pipeline.py", line 17, in initiate_data_transformation
    status = file.read().split("")[-1]
             ^^^^^^^^^^^^^^^^^^^^^
ValueError: empty separator
2025-04-06 17:11:42,929 - Datasciencelogger - ERROR - empty separator
Traceback (most recent call last):
  File "C:\Users\sylla\Desktop\MLOPS\Project1_with_deployment\Project1_Data_Science\main.py", line 35, in <module>
    obj.initiate_data_transformation()
  File "C:\Users\sylla\Desktop\MLOPS\Project1_with_deployment\Project1_Data_Science\src\Project1_Data_Science\pipeline\data_transforamtion_pipeline.py", line 28, in initiate_data_transformation
    raise e
  File "C:\Users\sylla\Desktop\MLOPS\Project1_with_deployment\Project1_Data_Science\src\Project1_Data_Science\pipeline\data_transforamtion_pipeline.py", line 17, in initiate_data_transformation
    status = file.read().split("")[-1]
             ^^^^^^^^^^^^^^^^^^^^^
ValueError: empty separator
2025-04-06 17:12:45,193 - Datasciencelogger - INFO - Bienvenue dans mon projet de data science !
2025-04-06 17:12:45,194 - Datasciencelogger - INFO - >>>>>>>>>>>>>>>>>>>> Data Ingestion stage started <<<<<<<<<<<<<<<<<<<<
2025-04-06 17:12:45,213 - Datasciencelogger - INFO - created directory at: artifacts
2025-04-06 17:12:45,213 - Datasciencelogger - INFO - created directory at: artifacts/data_ingestion
2025-04-06 17:12:45,222 - Datasciencelogger - INFO - File already exists: artifacts/data_ingestion/data.zip
2025-04-06 17:12:45,248 - Datasciencelogger - INFO - Extracted files to artifacts/data_ingestion
2025-04-06 17:12:45,252 - Datasciencelogger - INFO - >>>>>>>>>>>>>>>>>>>> Data Ingestion stage completed <<<<<<<<<<<<<<<<<<<<
2025-04-06 17:12:45,254 - Datasciencelogger - INFO - >>>>>>>>>>>>>>>>>>>> Data Validation stage started <<<<<<<<<<<<<<<<<<<<
2025-04-06 17:12:45,276 - Datasciencelogger - INFO - created directory at: artifacts
2025-04-06 17:12:45,288 - Datasciencelogger - INFO - created directory at: artifacts/data_validation
2025-04-06 17:12:45,317 - Datasciencelogger - INFO - Data loaded successfully for validation.
2025-04-06 17:12:45,322 - Datasciencelogger - INFO - Column fixed acidity is in the schema.
2025-04-06 17:12:45,322 - Datasciencelogger - INFO - Column volatile acidity is in the schema.
2025-04-06 17:12:45,332 - Datasciencelogger - INFO - Column citric acid is in the schema.
2025-04-06 17:12:45,335 - Datasciencelogger - INFO - Column residual sugar is in the schema.
2025-04-06 17:12:45,339 - Datasciencelogger - INFO - Column chlorides is in the schema.
2025-04-06 17:12:45,342 - Datasciencelogger - INFO - Column free sulfur dioxide is in the schema.
2025-04-06 17:12:45,350 - Datasciencelogger - INFO - Column total sulfur dioxide is in the schema.
2025-04-06 17:12:45,355 - Datasciencelogger - INFO - Column density is in the schema.
2025-04-06 17:12:45,355 - Datasciencelogger - INFO - Column pH is in the schema.
2025-04-06 17:12:45,364 - Datasciencelogger - INFO - Column sulphates is in the schema.
2025-04-06 17:12:45,368 - Datasciencelogger - INFO - Column alcohol is in the schema.
2025-04-06 17:12:45,372 - Datasciencelogger - INFO - Column quality is in the schema.
2025-04-06 17:12:45,372 - Datasciencelogger - INFO - Data validation completed successfully.
2025-04-06 17:12:45,372 - Datasciencelogger - INFO - >>>>>>>>>>>>>>>>>>>> Data Validation stage completed <<<<<<<<<<<<<<<<<<<<
2025-04-06 17:12:45,372 - Datasciencelogger - INFO - >>>>>>>>>>>>>>>>>>>> Data Transformation stage started <<<<<<<<<<<<<<<<<<<<
2025-04-06 17:12:45,374 - Datasciencelogger - ERROR - Data validation failed (See data Schema). Data transformation skipped.
Traceback (most recent call last):
  File "C:\Users\sylla\Desktop\MLOPS\Project1_with_deployment\Project1_Data_Science\src\Project1_Data_Science\pipeline\data_transforamtion_pipeline.py", line 25, in initiate_data_transformation
    raise Exception(f"Data validation failed (See data Schema). Data transformation skipped.")
Exception: Data validation failed (See data Schema). Data transformation skipped.
2025-04-06 17:12:45,374 - Datasciencelogger - ERROR - Data validation failed (See data Schema). Data transformation skipped.
Traceback (most recent call last):
  File "C:\Users\sylla\Desktop\MLOPS\Project1_with_deployment\Project1_Data_Science\main.py", line 35, in <module>
    obj.initiate_data_transformation()
  File "C:\Users\sylla\Desktop\MLOPS\Project1_with_deployment\Project1_Data_Science\src\Project1_Data_Science\pipeline\data_transforamtion_pipeline.py", line 28, in initiate_data_transformation
    raise e
  File "C:\Users\sylla\Desktop\MLOPS\Project1_with_deployment\Project1_Data_Science\src\Project1_Data_Science\pipeline\data_transforamtion_pipeline.py", line 25, in initiate_data_transformation
    raise Exception(f"Data validation failed (See data Schema). Data transformation skipped.")
Exception: Data validation failed (See data Schema). Data transformation skipped.
2025-04-06 17:19:29,408 - Datasciencelogger - INFO - Bienvenue dans mon projet de data science !
2025-04-06 17:19:29,424 - Datasciencelogger - INFO - >>>>>>>>>>>>>>>>>>>> Data Ingestion stage started <<<<<<<<<<<<<<<<<<<<
2025-04-06 17:19:29,506 - Datasciencelogger - INFO - created directory at: artifacts
2025-04-06 17:19:29,538 - Datasciencelogger - INFO - created directory at: artifacts/data_ingestion
2025-04-06 17:19:29,538 - Datasciencelogger - INFO - File already exists: artifacts/data_ingestion/data.zip
2025-04-06 17:19:29,790 - Datasciencelogger - INFO - Extracted files to artifacts/data_ingestion
2025-04-06 17:19:29,827 - Datasciencelogger - INFO - >>>>>>>>>>>>>>>>>>>> Data Ingestion stage completed <<<<<<<<<<<<<<<<<<<<
2025-04-06 17:19:29,839 - Datasciencelogger - INFO - >>>>>>>>>>>>>>>>>>>> Data Validation stage started <<<<<<<<<<<<<<<<<<<<
2025-04-06 17:19:29,991 - Datasciencelogger - INFO - created directory at: artifacts
2025-04-06 17:19:29,999 - Datasciencelogger - INFO - created directory at: artifacts/data_validation
2025-04-06 17:19:30,022 - Datasciencelogger - INFO - Data loaded successfully for validation.
2025-04-06 17:19:30,071 - Datasciencelogger - INFO - Column fixed acidity is in the schema.
2025-04-06 17:19:30,098 - Datasciencelogger - INFO - Column volatile acidity is in the schema.
2025-04-06 17:19:30,122 - Datasciencelogger - INFO - Column citric acid is in the schema.
2025-04-06 17:19:30,134 - Datasciencelogger - INFO - Column residual sugar is in the schema.
2025-04-06 17:19:30,139 - Datasciencelogger - INFO - Column chlorides is in the schema.
2025-04-06 17:19:30,143 - Datasciencelogger - INFO - Column free sulfur dioxide is in the schema.
2025-04-06 17:19:30,143 - Datasciencelogger - INFO - Column total sulfur dioxide is in the schema.
2025-04-06 17:19:30,150 - Datasciencelogger - INFO - Column density is in the schema.
2025-04-06 17:19:30,156 - Datasciencelogger - INFO - Column pH is in the schema.
2025-04-06 17:19:30,156 - Datasciencelogger - INFO - Column sulphates is in the schema.
2025-04-06 17:19:30,164 - Datasciencelogger - INFO - Column alcohol is in the schema.
2025-04-06 17:19:30,172 - Datasciencelogger - INFO - Column quality is in the schema.
2025-04-06 17:19:30,172 - Datasciencelogger - INFO - Data validation completed successfully.
2025-04-06 17:19:30,172 - Datasciencelogger - INFO - >>>>>>>>>>>>>>>>>>>> Data Validation stage completed <<<<<<<<<<<<<<<<<<<<
2025-04-06 17:19:30,172 - Datasciencelogger - INFO - >>>>>>>>>>>>>>>>>>>> Data Transformation stage started <<<<<<<<<<<<<<<<<<<<
2025-04-06 17:19:30,172 - Datasciencelogger - ERROR - Data validation failed (See data Schema). Data transformation skipped.
Traceback (most recent call last):
  File "C:\Users\sylla\Desktop\MLOPS\Project1_with_deployment\Project1_Data_Science\src\Project1_Data_Science\pipeline\data_transforamtion_pipeline.py", line 25, in initiate_data_transformation
    raise Exception(f"Data validation failed (See data Schema). Data transformation skipped.")
Exception: Data validation failed (See data Schema). Data transformation skipped.
2025-04-06 17:19:30,183 - Datasciencelogger - ERROR - Data validation failed (See data Schema). Data transformation skipped.
Traceback (most recent call last):
  File "C:\Users\sylla\Desktop\MLOPS\Project1_with_deployment\Project1_Data_Science\main.py", line 35, in <module>
    obj.initiate_data_transformation()
  File "C:\Users\sylla\Desktop\MLOPS\Project1_with_deployment\Project1_Data_Science\src\Project1_Data_Science\pipeline\data_transforamtion_pipeline.py", line 28, in initiate_data_transformation
    raise e
  File "C:\Users\sylla\Desktop\MLOPS\Project1_with_deployment\Project1_Data_Science\src\Project1_Data_Science\pipeline\data_transforamtion_pipeline.py", line 25, in initiate_data_transformation
    raise Exception(f"Data validation failed (See data Schema). Data transformation skipped.")
Exception: Data validation failed (See data Schema). Data transformation skipped.
2025-04-06 17:20:23,458 - Datasciencelogger - INFO - Bienvenue dans mon projet de data science !
2025-04-06 17:20:23,459 - Datasciencelogger - INFO - >>>>>>>>>>>>>>>>>>>> Data Ingestion stage started <<<<<<<<<<<<<<<<<<<<
2025-04-06 17:20:23,472 - Datasciencelogger - INFO - created directory at: artifacts
2025-04-06 17:20:23,474 - Datasciencelogger - INFO - created directory at: artifacts/data_ingestion
2025-04-06 17:20:23,476 - Datasciencelogger - INFO - File already exists: artifacts/data_ingestion/data.zip
2025-04-06 17:20:23,495 - Datasciencelogger - INFO - Extracted files to artifacts/data_ingestion
2025-04-06 17:20:23,498 - Datasciencelogger - INFO - >>>>>>>>>>>>>>>>>>>> Data Ingestion stage completed <<<<<<<<<<<<<<<<<<<<
2025-04-06 17:20:23,498 - Datasciencelogger - INFO - >>>>>>>>>>>>>>>>>>>> Data Validation stage started <<<<<<<<<<<<<<<<<<<<
2025-04-06 17:20:23,537 - Datasciencelogger - INFO - created directory at: artifacts
2025-04-06 17:20:23,560 - Datasciencelogger - INFO - created directory at: artifacts/data_validation
2025-04-06 17:20:23,589 - Datasciencelogger - INFO - Data loaded successfully for validation.
2025-04-06 17:20:23,606 - Datasciencelogger - INFO - Column fixed acidity is in the schema.
2025-04-06 17:20:23,612 - Datasciencelogger - INFO - Column volatile acidity is in the schema.
2025-04-06 17:20:23,612 - Datasciencelogger - INFO - Column citric acid is in the schema.
2025-04-06 17:20:23,625 - Datasciencelogger - INFO - Column residual sugar is in the schema.
2025-04-06 17:20:23,625 - Datasciencelogger - INFO - Column chlorides is in the schema.
2025-04-06 17:20:23,634 - Datasciencelogger - INFO - Column free sulfur dioxide is in the schema.
2025-04-06 17:20:23,643 - Datasciencelogger - INFO - Column total sulfur dioxide is in the schema.
2025-04-06 17:20:23,644 - Datasciencelogger - INFO - Column density is in the schema.
2025-04-06 17:20:23,644 - Datasciencelogger - INFO - Column pH is in the schema.
2025-04-06 17:20:23,662 - Datasciencelogger - INFO - Column sulphates is in the schema.
2025-04-06 17:20:23,680 - Datasciencelogger - INFO - Column alcohol is in the schema.
2025-04-06 17:20:23,695 - Datasciencelogger - INFO - Column quality is in the schema.
2025-04-06 17:20:23,699 - Datasciencelogger - INFO - Data validation completed successfully.
2025-04-06 17:20:23,709 - Datasciencelogger - INFO - >>>>>>>>>>>>>>>>>>>> Data Validation stage completed <<<<<<<<<<<<<<<<<<<<
2025-04-06 17:20:23,716 - Datasciencelogger - INFO - >>>>>>>>>>>>>>>>>>>> Data Transformation stage started <<<<<<<<<<<<<<<<<<<<
2025-04-06 17:20:23,778 - Datasciencelogger - INFO - created directory at: artifacts
2025-04-06 17:20:23,782 - Datasciencelogger - INFO - created directory at: artifacts/data_transformation
2025-04-06 17:20:23,782 - Datasciencelogger - INFO - Splitting data into train and test sets.
2025-04-06 17:20:23,916 - Datasciencelogger - INFO - Data splitting completed.
2025-04-06 17:20:23,916 - Datasciencelogger - INFO - (1279, 12)
2025-04-06 17:20:23,919 - Datasciencelogger - INFO - (320, 12)
2025-04-06 17:20:23,926 - Datasciencelogger - INFO - Data transformation completed.
2025-04-06 17:20:23,928 - Datasciencelogger - INFO - >>>>>>>>>>>>>>>>>>>> Data Transformation stage completed <<<<<<<<<<<<<<<<<<<<
2025-04-09 10:36:58,713 - Datasciencelogger - INFO - created directory at: artifacts
2025-04-09 10:36:58,737 - Datasciencelogger - INFO - created directory at: artifacts
2025-04-09 10:36:58,753 - Datasciencelogger - ERROR - "'ConfigBox' object has no attribute 'li_ratio'"
Traceback (most recent call last):
  File "c:\Users\sylla\Desktop\MLOPS\Project1_with_deployment\Project1_Data_Science\mon_env\Lib\site-packages\box\box.py", line 503, in __getitem__
    return super().__getitem__(item)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'li_ratio'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\sylla\Desktop\MLOPS\Project1_with_deployment\Project1_Data_Science\mon_env\Lib\site-packages\box\box.py", line 536, in __getattr__
    value = self.__getitem__(item, _ignore_default=True)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sylla\Desktop\MLOPS\Project1_with_deployment\Project1_Data_Science\mon_env\Lib\site-packages\box\box.py", line 524, in __getitem__
    raise BoxKeyError(str(err)) from _exception_cause(err)
box.exceptions.BoxKeyError: "'li_ratio'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\sylla\Desktop\MLOPS\Project1_with_deployment\Project1_Data_Science\mon_env\Lib\site-packages\box\box.py", line 538, in __getattr__
    value = object.__getattribute__(self, item)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigBox' object has no attribute 'li_ratio'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\sylla\Desktop\MLOPS\Project1_with_deployment\Project1_Data_Science\mon_env\Lib\site-packages\box\config_box.py", line 28, in __getattr__
    return super().__getattr__(item)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sylla\Desktop\MLOPS\Project1_with_deployment\Project1_Data_Science\mon_env\Lib\site-packages\box\box.py", line 552, in __getattr__
    raise BoxKeyError(str(err)) from _exception_cause(err)
box.exceptions.BoxKeyError: "'ConfigBox' object has no attribute 'li_ratio'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\sylla\Desktop\MLOPS\Project1_with_deployment\Project1_Data_Science\mon_env\Lib\site-packages\box\box.py", line 503, in __getitem__
    return super().__getitem__(item)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'li_ratio'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\sylla\Desktop\MLOPS\Project1_with_deployment\Project1_Data_Science\mon_env\Lib\site-packages\box\box.py", line 536, in __getattr__
    value = self.__getitem__(item, _ignore_default=True)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sylla\Desktop\MLOPS\Project1_with_deployment\Project1_Data_Science\mon_env\Lib\site-packages\box\box.py", line 524, in __getitem__
    raise BoxKeyError(str(err)) from _exception_cause(err)
box.exceptions.BoxKeyError: "'li_ratio'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\sylla\Desktop\MLOPS\Project1_with_deployment\Project1_Data_Science\mon_env\Lib\site-packages\box\box.py", line 538, in __getattr__
    value = object.__getattribute__(self, item)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigBox' object has no attribute 'li_ratio'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\sylla\AppData\Local\Temp\ipykernel_1772\1306516604.py", line 3, in <module>
    model_trainer_config = config.get_model_trainer_config()
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sylla\AppData\Local\Temp\ipykernel_1772\2508490259.py", line 29, in get_model_trainer_config
    li_ratio=params.li_ratio,
             ^^^^^^^^^^^^^^^
  File "c:\Users\sylla\Desktop\MLOPS\Project1_with_deployment\Project1_Data_Science\mon_env\Lib\site-packages\box\config_box.py", line 30, in __getattr__
    return super().__getattr__(item.lower())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sylla\Desktop\MLOPS\Project1_with_deployment\Project1_Data_Science\mon_env\Lib\site-packages\box\box.py", line 552, in __getattr__
    raise BoxKeyError(str(err)) from _exception_cause(err)
box.exceptions.BoxKeyError: "'ConfigBox' object has no attribute 'li_ratio'"
2025-04-09 10:39:20,890 - Datasciencelogger - INFO - created directory at: artifacts
2025-04-09 10:39:20,924 - Datasciencelogger - INFO - created directory at: artifacts
2025-04-09 10:39:20,933 - Datasciencelogger - ERROR - "'ConfigBox' object has no attribute 'li_ratio'"
Traceback (most recent call last):
  File "c:\Users\sylla\Desktop\MLOPS\Project1_with_deployment\Project1_Data_Science\mon_env\Lib\site-packages\box\box.py", line 503, in __getitem__
    return super().__getitem__(item)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'li_ratio'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\sylla\Desktop\MLOPS\Project1_with_deployment\Project1_Data_Science\mon_env\Lib\site-packages\box\box.py", line 536, in __getattr__
    value = self.__getitem__(item, _ignore_default=True)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sylla\Desktop\MLOPS\Project1_with_deployment\Project1_Data_Science\mon_env\Lib\site-packages\box\box.py", line 524, in __getitem__
    raise BoxKeyError(str(err)) from _exception_cause(err)
box.exceptions.BoxKeyError: "'li_ratio'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\sylla\Desktop\MLOPS\Project1_with_deployment\Project1_Data_Science\mon_env\Lib\site-packages\box\box.py", line 538, in __getattr__
    value = object.__getattribute__(self, item)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigBox' object has no attribute 'li_ratio'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\sylla\Desktop\MLOPS\Project1_with_deployment\Project1_Data_Science\mon_env\Lib\site-packages\box\config_box.py", line 28, in __getattr__
    return super().__getattr__(item)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sylla\Desktop\MLOPS\Project1_with_deployment\Project1_Data_Science\mon_env\Lib\site-packages\box\box.py", line 552, in __getattr__
    raise BoxKeyError(str(err)) from _exception_cause(err)
box.exceptions.BoxKeyError: "'ConfigBox' object has no attribute 'li_ratio'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\sylla\Desktop\MLOPS\Project1_with_deployment\Project1_Data_Science\mon_env\Lib\site-packages\box\box.py", line 503, in __getitem__
    return super().__getitem__(item)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'li_ratio'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\sylla\Desktop\MLOPS\Project1_with_deployment\Project1_Data_Science\mon_env\Lib\site-packages\box\box.py", line 536, in __getattr__
    value = self.__getitem__(item, _ignore_default=True)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sylla\Desktop\MLOPS\Project1_with_deployment\Project1_Data_Science\mon_env\Lib\site-packages\box\box.py", line 524, in __getitem__
    raise BoxKeyError(str(err)) from _exception_cause(err)
box.exceptions.BoxKeyError: "'li_ratio'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\sylla\Desktop\MLOPS\Project1_with_deployment\Project1_Data_Science\mon_env\Lib\site-packages\box\box.py", line 538, in __getattr__
    value = object.__getattribute__(self, item)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigBox' object has no attribute 'li_ratio'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\sylla\AppData\Local\Temp\ipykernel_1772\1306516604.py", line 3, in <module>
    model_trainer_config = config.get_model_trainer_config()
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sylla\AppData\Local\Temp\ipykernel_1772\2508490259.py", line 29, in get_model_trainer_config
    li_ratio=params.li_ratio,
             ^^^^^^^^^^^^^^^
  File "c:\Users\sylla\Desktop\MLOPS\Project1_with_deployment\Project1_Data_Science\mon_env\Lib\site-packages\box\config_box.py", line 30, in __getattr__
    return super().__getattr__(item.lower())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sylla\Desktop\MLOPS\Project1_with_deployment\Project1_Data_Science\mon_env\Lib\site-packages\box\box.py", line 552, in __getattr__
    raise BoxKeyError(str(err)) from _exception_cause(err)
box.exceptions.BoxKeyError: "'ConfigBox' object has no attribute 'li_ratio'"
2025-04-09 10:39:59,058 - Datasciencelogger - INFO - created directory at: artifacts
2025-04-09 10:39:59,066 - Datasciencelogger - INFO - created directory at: artifacts
2025-04-09 10:39:59,072 - Datasciencelogger - ERROR - "'ConfigBox' object has no attribute 'li_ratio'"
Traceback (most recent call last):
  File "c:\Users\sylla\Desktop\MLOPS\Project1_with_deployment\Project1_Data_Science\mon_env\Lib\site-packages\box\box.py", line 503, in __getitem__
    return super().__getitem__(item)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'li_ratio'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\sylla\Desktop\MLOPS\Project1_with_deployment\Project1_Data_Science\mon_env\Lib\site-packages\box\box.py", line 536, in __getattr__
    value = self.__getitem__(item, _ignore_default=True)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sylla\Desktop\MLOPS\Project1_with_deployment\Project1_Data_Science\mon_env\Lib\site-packages\box\box.py", line 524, in __getitem__
    raise BoxKeyError(str(err)) from _exception_cause(err)
box.exceptions.BoxKeyError: "'li_ratio'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\sylla\Desktop\MLOPS\Project1_with_deployment\Project1_Data_Science\mon_env\Lib\site-packages\box\box.py", line 538, in __getattr__
    value = object.__getattribute__(self, item)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigBox' object has no attribute 'li_ratio'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\sylla\Desktop\MLOPS\Project1_with_deployment\Project1_Data_Science\mon_env\Lib\site-packages\box\config_box.py", line 28, in __getattr__
    return super().__getattr__(item)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sylla\Desktop\MLOPS\Project1_with_deployment\Project1_Data_Science\mon_env\Lib\site-packages\box\box.py", line 552, in __getattr__
    raise BoxKeyError(str(err)) from _exception_cause(err)
box.exceptions.BoxKeyError: "'ConfigBox' object has no attribute 'li_ratio'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\sylla\Desktop\MLOPS\Project1_with_deployment\Project1_Data_Science\mon_env\Lib\site-packages\box\box.py", line 503, in __getitem__
    return super().__getitem__(item)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'li_ratio'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\sylla\Desktop\MLOPS\Project1_with_deployment\Project1_Data_Science\mon_env\Lib\site-packages\box\box.py", line 536, in __getattr__
    value = self.__getitem__(item, _ignore_default=True)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sylla\Desktop\MLOPS\Project1_with_deployment\Project1_Data_Science\mon_env\Lib\site-packages\box\box.py", line 524, in __getitem__
    raise BoxKeyError(str(err)) from _exception_cause(err)
box.exceptions.BoxKeyError: "'li_ratio'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\sylla\Desktop\MLOPS\Project1_with_deployment\Project1_Data_Science\mon_env\Lib\site-packages\box\box.py", line 538, in __getattr__
    value = object.__getattribute__(self, item)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigBox' object has no attribute 'li_ratio'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\sylla\AppData\Local\Temp\ipykernel_1772\1306516604.py", line 3, in <module>
    model_trainer_config = config.get_model_trainer_config()
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sylla\AppData\Local\Temp\ipykernel_1772\2508490259.py", line 29, in get_model_trainer_config
    li_ratio=params.li_ratio,
             ^^^^^^^^^^^^^^^
  File "c:\Users\sylla\Desktop\MLOPS\Project1_with_deployment\Project1_Data_Science\mon_env\Lib\site-packages\box\config_box.py", line 30, in __getattr__
    return super().__getattr__(item.lower())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sylla\Desktop\MLOPS\Project1_with_deployment\Project1_Data_Science\mon_env\Lib\site-packages\box\box.py", line 552, in __getattr__
    raise BoxKeyError(str(err)) from _exception_cause(err)
box.exceptions.BoxKeyError: "'ConfigBox' object has no attribute 'li_ratio'"
2025-04-09 10:40:47,597 - Datasciencelogger - INFO - created directory at: artifacts
2025-04-09 10:40:47,609 - Datasciencelogger - INFO - created directory at: artifacts
2025-04-09 10:40:47,615 - Datasciencelogger - ERROR - ModelTrainerConfig.__init__() got an unexpected keyword argument 'l1_ratio'
Traceback (most recent call last):
  File "C:\Users\sylla\AppData\Local\Temp\ipykernel_1772\1306516604.py", line 3, in <module>
    model_trainer_config = config.get_model_trainer_config()
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sylla\AppData\Local\Temp\ipykernel_1772\129555931.py", line 22, in get_model_trainer_config
    model_trainer_config = ModelTrainerConfig(
                           ^^^^^^^^^^^^^^^^^^^
TypeError: ModelTrainerConfig.__init__() got an unexpected keyword argument 'l1_ratio'
2025-04-09 10:45:39,884 - Datasciencelogger - INFO - created directory at: artifacts
2025-04-09 10:45:39,891 - Datasciencelogger - INFO - created directory at: artifacts
2025-04-09 10:45:39,895 - Datasciencelogger - INFO - Training model with config: ModelTrainerConfig(root_dir='artifacts/model_trainer', train_data_path='artifacts/data_transformation/train.csv', test_data_path='artifacts/data_transformation/test.csv', model_name='model.joblib', alpha=0.2, random_state=42, l1_ratio=0.1, target_column='quality')
2025-04-09 10:45:40,428 - Datasciencelogger - ERROR - [Errno 2] No such file or directory: 'artifacts/model_trainer\\model.joblib'
Traceback (most recent call last):
  File "C:\Users\sylla\AppData\Local\Temp\ipykernel_16012\1306516604.py", line 5, in <module>
    model_trainer.train()
  File "C:\Users\sylla\AppData\Local\Temp\ipykernel_16012\3088706761.py", line 31, in train
    joblib.dump(model_en, model_path)
  File "c:\Users\sylla\Desktop\MLOPS\Project1_with_deployment\Project1_Data_Science\mon_env\Lib\site-packages\joblib\numpy_pickle.py", line 552, in dump
    with open(filename, 'wb') as f:
         ^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'artifacts/model_trainer\\model.joblib'
2025-04-09 10:55:13,817 - Datasciencelogger - INFO - created directory at: artifacts
2025-04-09 10:55:13,824 - Datasciencelogger - INFO - created directory at: artifacts/model_trainer
2025-04-09 10:55:13,828 - Datasciencelogger - INFO - Training model with config: ModelTrainerConfig(root_dir='artifacts/model_trainer', train_data_path='artifacts/data_transformation/train.csv', test_data_path='artifacts/data_transformation/test.csv', model_name='model.joblib', alpha=0.2, random_state=42, l1_ratio=0.1, target_column='quality')
2025-04-09 10:55:13,980 - Datasciencelogger - INFO - Model saved at: artifacts/model_trainer\model.joblib
2025-04-09 11:50:58,695 - Datasciencelogger - INFO - Bienvenue dans mon projet de data science !
2025-04-09 11:50:58,699 - Datasciencelogger - INFO - >>>>>>>>>>>>>>>>>>>> Data Ingestion stage started <<<<<<<<<<<<<<<<<<<<
2025-04-09 11:50:58,821 - Datasciencelogger - INFO - created directory at: artifacts
2025-04-09 11:50:58,835 - Datasciencelogger - INFO - created directory at: artifacts/data_ingestion
2025-04-09 11:50:58,863 - Datasciencelogger - INFO - File already exists: artifacts/data_ingestion/data.zip
2025-04-09 11:50:58,945 - Datasciencelogger - INFO - Extracted files to artifacts/data_ingestion
2025-04-09 11:50:58,948 - Datasciencelogger - INFO - >>>>>>>>>>>>>>>>>>>> Data Ingestion stage completed <<<<<<<<<<<<<<<<<<<<
2025-04-09 11:50:58,949 - Datasciencelogger - INFO - >>>>>>>>>>>>>>>>>>>> Data Validation stage started <<<<<<<<<<<<<<<<<<<<
2025-04-09 11:50:58,972 - Datasciencelogger - INFO - created directory at: artifacts
2025-04-09 11:50:58,976 - Datasciencelogger - INFO - created directory at: artifacts/data_validation
2025-04-09 11:50:59,020 - Datasciencelogger - INFO - Data loaded successfully for validation.
2025-04-09 11:50:59,034 - Datasciencelogger - INFO - Column fixed acidity is in the schema.
2025-04-09 11:50:59,037 - Datasciencelogger - INFO - Column volatile acidity is in the schema.
2025-04-09 11:50:59,040 - Datasciencelogger - INFO - Column citric acid is in the schema.
2025-04-09 11:50:59,047 - Datasciencelogger - INFO - Column residual sugar is in the schema.
2025-04-09 11:50:59,051 - Datasciencelogger - INFO - Column chlorides is in the schema.
2025-04-09 11:50:59,053 - Datasciencelogger - INFO - Column free sulfur dioxide is in the schema.
2025-04-09 11:50:59,055 - Datasciencelogger - INFO - Column total sulfur dioxide is in the schema.
2025-04-09 11:50:59,063 - Datasciencelogger - INFO - Column density is in the schema.
2025-04-09 11:50:59,065 - Datasciencelogger - INFO - Column pH is in the schema.
2025-04-09 11:50:59,067 - Datasciencelogger - INFO - Column sulphates is in the schema.
2025-04-09 11:50:59,069 - Datasciencelogger - INFO - Column alcohol is in the schema.
2025-04-09 11:50:59,072 - Datasciencelogger - INFO - Column quality is in the schema.
2025-04-09 11:50:59,072 - Datasciencelogger - INFO - Data validation completed successfully.
2025-04-09 11:50:59,073 - Datasciencelogger - INFO - >>>>>>>>>>>>>>>>>>>> Data Validation stage completed <<<<<<<<<<<<<<<<<<<<
2025-04-09 11:50:59,076 - Datasciencelogger - INFO - >>>>>>>>>>>>>>>>>>>> Data Transformation stage started <<<<<<<<<<<<<<<<<<<<
2025-04-09 11:50:59,102 - Datasciencelogger - INFO - created directory at: artifacts
2025-04-09 11:50:59,104 - Datasciencelogger - INFO - created directory at: artifacts/data_transformation
2025-04-09 11:50:59,107 - Datasciencelogger - INFO - Splitting data into train and test sets.
2025-04-09 11:50:59,249 - Datasciencelogger - INFO - Data splitting completed.
2025-04-09 11:50:59,250 - Datasciencelogger - INFO - (1279, 12)
2025-04-09 11:50:59,251 - Datasciencelogger - INFO - (320, 12)
2025-04-09 11:50:59,253 - Datasciencelogger - INFO - Data transformation completed.
2025-04-09 11:50:59,254 - Datasciencelogger - INFO - >>>>>>>>>>>>>>>>>>>> Data Transformation stage completed <<<<<<<<<<<<<<<<<<<<
2025-04-09 11:50:59,256 - Datasciencelogger - INFO - >>>>>>>>>>>>>>>>>>>> Model Trainer stage started <<<<<<<<<<<<<<<<<<<<
2025-04-09 11:50:59,284 - Datasciencelogger - INFO - created directory at: artifacts
2025-04-09 11:50:59,286 - Datasciencelogger - INFO - created directory at: artifacts/model_trainer
2025-04-09 11:50:59,286 - Datasciencelogger - ERROR - ModelTrainer.__init__() got an unexpected keyword argument 'Config'
Traceback (most recent call last):
  File "C:\Users\sylla\Desktop\MLOPS\Project1_with_deployment\Project1_Data_Science\main.py", line 48, in <module>
    obj.initiate_model_training()
  File "C:\Users\sylla\Desktop\MLOPS\Project1_with_deployment\Project1_Data_Science\src\Project1_Data_Science\pipeline\model_trainer_pipeline.py", line 16, in initiate_model_training
    model_trainer_config = ModelTrainer(Config=model_trainer_config)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelTrainer.__init__() got an unexpected keyword argument 'Config'
2025-04-09 11:53:55,217 - Datasciencelogger - INFO - Bienvenue dans mon projet de data science !
2025-04-09 11:53:55,220 - Datasciencelogger - INFO - >>>>>>>>>>>>>>>>>>>> Data Ingestion stage started <<<<<<<<<<<<<<<<<<<<
2025-04-09 11:53:55,300 - Datasciencelogger - INFO - created directory at: artifacts
2025-04-09 11:53:55,310 - Datasciencelogger - INFO - created directory at: artifacts/data_ingestion
2025-04-09 11:53:55,315 - Datasciencelogger - INFO - File already exists: artifacts/data_ingestion/data.zip
2025-04-09 11:53:55,339 - Datasciencelogger - INFO - Extracted files to artifacts/data_ingestion
2025-04-09 11:53:55,347 - Datasciencelogger - INFO - >>>>>>>>>>>>>>>>>>>> Data Ingestion stage completed <<<<<<<<<<<<<<<<<<<<
2025-04-09 11:53:55,356 - Datasciencelogger - INFO - >>>>>>>>>>>>>>>>>>>> Data Validation stage started <<<<<<<<<<<<<<<<<<<<
2025-04-09 11:53:55,416 - Datasciencelogger - INFO - created directory at: artifacts
2025-04-09 11:53:55,425 - Datasciencelogger - INFO - created directory at: artifacts/data_validation
2025-04-09 11:53:55,464 - Datasciencelogger - INFO - Data loaded successfully for validation.
2025-04-09 11:53:55,480 - Datasciencelogger - INFO - Column fixed acidity is in the schema.
2025-04-09 11:53:55,495 - Datasciencelogger - INFO - Column volatile acidity is in the schema.
2025-04-09 11:53:55,499 - Datasciencelogger - INFO - Column citric acid is in the schema.
2025-04-09 11:53:55,502 - Datasciencelogger - INFO - Column residual sugar is in the schema.
2025-04-09 11:53:55,512 - Datasciencelogger - INFO - Column chlorides is in the schema.
2025-04-09 11:53:55,517 - Datasciencelogger - INFO - Column free sulfur dioxide is in the schema.
2025-04-09 11:53:55,525 - Datasciencelogger - INFO - Column total sulfur dioxide is in the schema.
2025-04-09 11:53:55,529 - Datasciencelogger - INFO - Column density is in the schema.
2025-04-09 11:53:55,534 - Datasciencelogger - INFO - Column pH is in the schema.
2025-04-09 11:53:55,545 - Datasciencelogger - INFO - Column sulphates is in the schema.
2025-04-09 11:53:55,549 - Datasciencelogger - INFO - Column alcohol is in the schema.
2025-04-09 11:53:55,551 - Datasciencelogger - INFO - Column quality is in the schema.
2025-04-09 11:53:55,557 - Datasciencelogger - INFO - Data validation completed successfully.
2025-04-09 11:53:55,560 - Datasciencelogger - INFO - >>>>>>>>>>>>>>>>>>>> Data Validation stage completed <<<<<<<<<<<<<<<<<<<<
2025-04-09 11:53:55,567 - Datasciencelogger - INFO - >>>>>>>>>>>>>>>>>>>> Data Transformation stage started <<<<<<<<<<<<<<<<<<<<
2025-04-09 11:53:55,630 - Datasciencelogger - INFO - created directory at: artifacts
2025-04-09 11:53:55,659 - Datasciencelogger - INFO - created directory at: artifacts/data_transformation
2025-04-09 11:53:55,668 - Datasciencelogger - INFO - Splitting data into train and test sets.
2025-04-09 11:53:55,870 - Datasciencelogger - INFO - Data splitting completed.
2025-04-09 11:53:55,874 - Datasciencelogger - INFO - (1279, 12)
2025-04-09 11:53:55,875 - Datasciencelogger - INFO - (320, 12)
2025-04-09 11:53:55,878 - Datasciencelogger - INFO - Data transformation completed.
2025-04-09 11:53:55,883 - Datasciencelogger - INFO - >>>>>>>>>>>>>>>>>>>> Data Transformation stage completed <<<<<<<<<<<<<<<<<<<<
2025-04-09 11:53:55,885 - Datasciencelogger - INFO - >>>>>>>>>>>>>>>>>>>> Model Trainer stage started <<<<<<<<<<<<<<<<<<<<
2025-04-09 11:53:55,950 - Datasciencelogger - INFO - created directory at: artifacts
2025-04-09 11:53:55,962 - Datasciencelogger - INFO - created directory at: artifacts/model_trainer
2025-04-09 11:53:55,964 - Datasciencelogger - INFO - Training model with config: ModelTrainerConfig(root_dir='artifacts/model_trainer', train_data_path='artifacts/data_transformation/train.csv', test_data_path='artifacts/data_transformation/test.csv', model_name='model.joblib', alpha=0.2, random_state=42, l1_ratio=0.1, target_column='quality')
2025-04-09 11:53:56,020 - Datasciencelogger - INFO - Model saved at: artifacts/model_trainer\model.joblib
2025-04-09 11:53:56,023 - Datasciencelogger - INFO - Model Trainer stage completed successfully.
2025-04-09 11:53:56,027 - Datasciencelogger - INFO - >>>>>>>>>>>>>>>>>>>> Model Trainer stage completed <<<<<<<<<<<<<<<<<<<<
